### PR TITLE
Enhance Chef::Provider::CrowbarPacemakerService for the needs of compute nodes HA

### PR DESCRIPTION
**Pull request by vuntz**
We add two new flags, see commit messages for the details.

### CODE REVIEW

**Comment by vuntz** [comment]
This is hitting https://trello.com/c/30w2SCA0/128-c6-ha-waiting-for-testvm-booted-and-ping-returned-timed-out-in-testsetup-step and manila failures in tempest, but deployment and rest tempest were fine; so good enough for merging.

Any +1?

**Comment by aplanas** [comment]
in the first commit message 'un the cluster due' (in the cluster due ...)

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
> in the first commit message 'un the cluster due' (in the cluster due ...)

fixed (no code change)

**Comment by vuntz** [comment]
Still samefailures in gating (unrelated to this PR), so I still think it's fine to merge.

Just missing a last +1 :-)

**Comment by nkrinner** [comment]
+1

**Pull request merged**
