### PR TITLE
[4.0] pacemaker: add failure nodes to sync fail message (bsc#1083721)

### PR DESCRIPTION
**Pull request by matthewoliver**
The current "Some cluster nodes didn't set #{mark}!" isn't a very
usful message. And is a pretty common L3 bug with this simple message.

This is not very helpful for a bug report and it is a distraction from
the actual issue that happened elsewhere, as the customer could have been
looking at other nodes' logs instead of opening an SR right away.

This patch cleans up the logging to include not only the nodes that failed
but also adds the cluster name to each relevant log line. So it's clear
from the logs what pacemaker cluster the message is in reference to.
Which is useful for deployments with more then 1 HA cluster.

Adam already had a PR (202) to solve this, but unfortuantly the
underlying layout changed before it got a chance to merge. So
this patch has become a merge of both our patches to finally solve this
issue.

(cherry picked from commit 90bf282f955ed7ceb34afe2d65f189b6b1ceb1a9)

### CODE REVIEW

**Review by AbelNavarro — APPROVED** [review]

**Review by aspiers — APPROVED** [review]
The CI failure looks unrelated, so assuming that this is a straight cherry-pick, I'm +1 (actually +10000) for backporting this significant UX improvement, which should help reduce the most common FAQ we get from customers.

**Comment by nicolasbock** [comment]
I restarted the CI job

**Comment by AbelNavarro** [comment]
I also just restarted the CI job. The error looked unrelated, but you could actually see the extended debug info in place which is useful. Please don't let this backport die.

**Comment by aspiers** [comment]
I guess this is the extract from the CI failures @AbelNavarro was talking about (or one of them at least), which proves this is working:

```
[2019-06-07T13:29:43+00:00] FATAL: Cluster founder d52-54-77-77-01-01 didn't set keystone_certificates on cluster data! Timed out while waiting for the founder; please check either '/var/log/crowbar/chef-client/d52-54-77-77-01-01.vm1.cloud.suse.de.log' on the admin node or '/var/log/chef/client.log' on d52-54-77-77-01-01 to see what went wrong.
```

I suggest we wait for one more reviewer to approve and then merge.

**Comment by JanZerebecki** [comment]
This branch should now only receive important changes. This looks like it is not. Please reopen if you feel otherwise.

**Pull request closed without merging**
