### PR TITLE
Use pacemaker transactions for Horizon/Apache

### PR DESCRIPTION
**Pull request by abel-navarro**

### CODE REVIEW

**Comment by vuntz** [comment]
Ah, hrm, hadn't seen your PR: I also have some of this in https://github.com/crowbar/crowbar-ha/pull/51 (I can drop it there, if wanted)

**Comment by abel-navarro** [comment]
it's failing for me and investigating the issue currently:

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/horizon/recipes/server.rb
================================================================================

Chef::Exceptions::ValidationFailed
----------------------------------
Option action must be equal to one of: nothing, create, delete, start, stop, create!  You passed :update.

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/crowbar-pacemaker/recipes/apache.rb:56:in `block in from_file'
  /var/chef/cache/cookbooks/crowbar-pacemaker/recipes/apache.rb:52:in `from_file'
  /var/chef/cache/cookbooks/horizon/recipes/ha.rb:44:in `from_file'
  /var/chef/cache/cookbooks/horizon/recipes/server.rb:336:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/crowbar-pacemaker/recipes/apache.rb:

 49:  
 50:  transaction_objects = []
 51:  
 52:  pacemaker_primitive service_name do
 53:    agent agent_name
 54:    params apache_params
 55:    op apache_op
 56>>   action :update
 57:    only_if { CrowbarPacemakerHelper.is_cluster_founder?(node) }
 58:  end
 59:  transaction_objects << "pacemaker_primitive[#{service_name}]"
 60:  
 61:  clone_name = "cl-#{service_name}"
 62:  pacemaker_clone clone_name do
 63:    rsc service_name
 64:    action :update
 65:    only_if { CrowbarPacemakerHelper.is_cluster_founder?(node) }
```

**Comment by aspiers** [comment]
As discussed on IRC you need #46.

**Comment by dirkmueller** [comment]
@abel-navarro can you rebase?

**Comment by abel-navarro** [comment]
@dirkmueller This change has also been myde by @vuntz at https://github.com/crowbar/crowbar-ha/pull/51. It is probably easier to just drop this PR, since it only has one commit. If @vuntz agrees we can close this one.

**Comment by vuntz** [comment]
Ok, let's close this one.

**Pull request closed without merging**
