### PR TITLE
Revert change of default timeout for sync marks

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by aspiers** [comment]
+1 but why isn't this part of #61?

**Comment by aspiers** [comment]
Oh, you explained that in #61.

**Comment by tboerger** [comment]
:+1:

**Comment by aspiers** [comment]
Gate failed due to [c6-ha: neutron HTTP 502 in tempest (teardown of resources failed: Unexpected response code received) Trello](https://trello.com/c/E1545YDo/118-c6-ha-neutron-http-502-in-tempest-teardown-of-resources-failed-unexpected-response-code-received) - trying a rebuild now that we have all controllers with the right amount of memory; sometimes we get lucky and avoid the race.

**Comment by vuntz** [comment]
Hrm, indeed with more memory, things might not be as slow. Still leaving the "do not merge" tag as I'd feel more comfortable checking some logs to be sure.

**Comment by aspiers** [comment]
@vuntz Gate passed this time!  +1 for me but feel free to check logs before you merge.

**Comment by vuntz** [comment]
I'd like to try this in Cloud 7. @aspiers are you fine with that?

**Comment by aspiers** [comment]
@vuntz Yes.

**Pull request merged**
