### PR TITLE
Drop cman cookbook

### PR DESCRIPTION
**Pull request by vuntz**
It's not used, so not sure why we ship it.

cc @aspiers

### CODE REVIEW

**Comment by vuntz** [comment]
Note that gating fails because it's not able to remove files when building the package.

**Comment by tboerger** [comment]
LGTM

**Comment by rsalevsky** [comment]
+1

**Comment by aplanas** [comment]
The gating fails because some OBS error (or I think so). Relaunched the job (or I think so :)

**Comment by vuntz** [comment]
> The gating fails because some OBS error (or I think so). Relaunched the job (or I think so :)

See my earlier comment; gating doesnt seem to work when removing files.

**Comment by aplanas** [comment]
+1 I do not see any reference remaining for cman

**Pull request merged**
