### PR TITLE
Misc cleanup

### PR DESCRIPTION
**Pull request by aspiers**
Misc cleanup developed whilst working on [S32P3: compute #HA: support for atomic creation of resources and location constraints Trello](https://trello.com/c/WrI6NNVF/540-5-s32p3-compute-ha-support-for-atomic-creation-of-resources-and-location-constraints).  Submitted separately to keep the main PR down to a manageable size for easy review.

### CODE REVIEW

**Comment by aspiers** [comment]
Travis doesn't like the `require_relative` change for some reason.

**Comment by aspiers** [comment]
Seems to be a Ruby 2.1.0 bug where Chef doing a `class_eval` on a provider class causes the `require_relative` inside that class to break.  Not a problem with Ruby 2.2.1, but since we're still on 2.1, I've dropped the changes to the provider classes for now.

**Comment by vuntz** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by vuntz** [comment]
Gating can't be green because of .gitignore patching... Adam: are you fine to mege?

**Comment by vuntz** [comment]
> Adam: are you fine to mege?

He said yes :-)

**Pull request merged**
