### PR TITLE
pacemaker: Avoid calling crm for redefining resources while there's no diff

### PR DESCRIPTION
**Pull request by vuntz**
See both commit messages for the details on the two issues that are fixed.

### CODE REVIEW

**Comment by vuntz** [comment]
> commit message: /one-lien/one-line/

Thanks, fixed.

**Comment by aplanas** [comment]
+1

**Comment by jsuchome** [comment]
Looks correct. +1 (not tested)

**Comment by vuntz** [comment]
Like the other PR, we fail in manila in tempest (unrelated to this PR). Good enough for merging.

**Comment by aspiers** [comment]
Thanks, retrospective +1 although I'm curious about the `clone`.

**Pull request merged**
