### PR TITLE
apache, haproxy, notifications, stonith: Use new pacemaker_transaction LWRP to create resources

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by aspiers** [comment]
Looks good except the nitpicks.  Please rebase so that the gate environment isn't missing support for `:update` and `pacemaker_transaction`.

**Comment by vuntz** [comment]
Rebased.

**Comment by vuntz** [comment]
Tempest failed because of ceph (the now famous test_volume_boot_pattern failure).

**Comment by aspiers** [comment]
I think I'm +1 on this.  I guess by `test_volume_boot_pattern` failure you mean https://trello.com/c/pXHuvAd3 ?

**Comment by vuntz** [comment]
> I guess by test_volume_boot_pattern failure you mean https://trello.com/c/pXHuvAd3 ?

yes

**Comment by vuntz** [comment]
Looking for some additional +1. Anyone brave enough for this? :-)

**Comment by aplanas** [comment]
@vuntz I can only provide a completely uninformed +1 (and I am checking the code since this morning)

**Comment by aspiers** [comment]
@vuntz If the codeclimate failure annoys you, rebasing should fix it.

**Comment by vuntz** [comment]
Rebased, with no code change (as suggested by @aspiers) -- I'm considering the +1 as still valid, fwiw.

**Comment by aspiers** [comment]
Gate failed due to [c6: crowbar_batch (manila): Failed to validate proposal Trello](https://trello.com/c/IGdx9l4u/121-c6-crowbar-batch-manila-failed-to-validate-proposal).  May be fixed by https://github.com/SUSE-Cloud/automation/pull/771 so I'm trying a rebuild.

**Comment by nkrinner** [comment]
+1 from code review. But the gating failed with an cinder error it seems.

**Comment by aspiers** [comment]
@nkrinner What cinder error is that exactly?  Is there a Jenkins green card for it?

**Comment by vuntz** [comment]
FWIW, current gating error (`Server building... 0% completeERROR (ConnectionRefused): Unable to establish connection to http://cluster-data.vd4.cloud.suse.de:8774/v2.1/cb1b61aa315b440b927d3da31c641e10/servers/eee70470-e7c1-40fb-9523-c0ba991cd939`) is something really weird; it might be related to HA (although not this patch), but I'd need hb_report to be sure...

Re-triggering, and if it happens again, we should freeze the system.

**Pull request merged**
