### PR TITLE
ipmi: Use discovered IP in read-only mode (forward port)

### PR DESCRIPTION
**Pull request by skazi0**
forward port of #232

### CODE REVIEW

**Comment by skazi0** [comment]
[readonly IPMI - use existing IPMI settings - no bmc-nat](https://trello.com/c/Q7laJy5q/91-readonly-ipmi-use-existing-ipmi-settings-no-bmc-nat)

**Comment by matelakat** [comment]
Re-triggered CI

**Comment by matelakat** [comment]
zypper issue on CI again, so re-triggering.

**Comment by Itxaka** [comment]
issue seems now fixed on ci, retriggering

**Pull request merged**
