### PR TITLE
Remove "bc-" prefix of barclamp id's

### PR DESCRIPTION
**Pull request by vwallfahrer**

### CODE REVIEW

**Comment by tboerger** [comment]
Do we need some kind of migrations for already existing installations? Otherwise :+1:

**Comment by rsalevsky** [comment]
+1

**Comment by vuntz** [comment]
+1, but waiting for M5 to be released before merging.

**Comment by vuntz** [comment]
@vwallfahrer can you rebase?

**Comment by toabctl** [comment]
+1

**Pull request merged**
