### PR TITLE
[4.0] Fix a search for cluster founders.

### PR DESCRIPTION
**Pull request by jsuchome**
[:pacemaker][:founder] was changed from boolean to string recently

### CODE REVIEW

**Comment by Itxaka** [comment]
@jsuchome maybe we want to have the same in both 4.0 as master:

https://github.com/crowbar/crowbar-ha/commit/54c9d4204dcc063d9aa094b0c4213be68d2f47b2#diff-e7b8b7bb6c0a774ed453e208a7d19635R25

And 

https://github.com/crowbar/crowbar-ha/commit/54c9d4204dcc063d9aa094b0c4213be68d2f47b2#diff-e7b8b7bb6c0a774ed453e208a7d19635R47

Doesnt matter to me if those changes are cherry-picked from master to 4.0 or this PR is merged and then pushed to master, but having the same code on both is desired IMO.

**Comment by jsuchome** [comment]
@Itxaka I'll just manually sync this `4.0` code with master one...

**Comment by bbobrov** [comment]
I think that this introduced a regression. I am getting `undefined method `find' for Api::Node:Class` when trying to run prechecks for 7->8 upgrades. Reverting this patch helps.

**Comment by jsuchome** [comment]
@bbobrov you're right, but it's already fixed with https://github.com/crowbar/crowbar-ha/pull/310

**Pull request merged**
