### PR TITLE
more misc cleanup

### PR DESCRIPTION
**Pull request by aspiers**
Fairly generic cleanup which helps prepare for `pacemaker_transaction` LWRP.

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by vuntz** [comment]
Gating is red, but it deployed up to ceilometer. So unrelated to this PR, it's just the usual "HA gating is still not fully functional" issue.

**Comment by dirkmueller** [comment]
+1 , although I would wish more explanation in the commit https://github.com/aspiers/crowbar-ha/commit/bc0813d53c61fc62dfe94a8d59e5c22e98f4206b on why the change from ::TYPE to ::object_type is correct. pasting the full backtrace in the commit log is imho less relevant.

**Comment by aspiers** [comment]
@dirkmueller Good point, I can easily improve that.

**Comment by aspiers** [comment]
@dirkmueller Updated the text - is c0d0b27 better?

**Comment by dirkmueller** [comment]
@aspiers yes, thanks

**Pull request merged**
