### PR TITLE
Improvements for DRBD

### PR DESCRIPTION
**Pull request by vuntz**
Use variable sync rate config, and enable peer authentication.

### CODE REVIEW

**Comment by aspiers** [comment]
LGTM, why still WIP?

**Comment by vuntz** [comment]
@aspiers because mkcloud fails. It seems the sync slows down everything, and applying neutron took too long. So probably need to tweak the defaults :/

**Comment by toabctl** [comment]
I wonder why we have 20 GB as default size for the drbd block devices. We can speedup the sync by reducing the default size.

**Comment by vuntz** [comment]
> I wonder why we have 20 GB as default size for the drbd block devices. We can speedup the sync by reducing the default size.

Very good point; fixed in https://github.com/SUSE-Cloud/automation/pull/560

**Comment by toabctl** [comment]
> Very good point; fixed in SUSE-Cloud/automation#560

If that's not enough, we could increase the sync rate Temporary in mkcloud. See https://drbd.linbit.com/users-guide/s-configure-sync-rate.html section 6.10.2

**Comment by vuntz** [comment]
Removed WIP; seems good enough after changing defaults.

**Comment by toabctl** [comment]
+1

**Comment by vuntz** [comment]
added link to bugzilla, no code change

**Comment by toabctl** [comment]
still +1

**Comment by vuntz** [comment]
Worked well in local testing.

**Comment by vuntz** [comment]
Note that we can either wait for non-HA gating (which is useless) or HA gating (which will be red because of other issues).

**Comment by aspiers** [comment]
@vuntz https://github.com/SUSE-Cloud/automation/pull/549 will ensure that the gate for this repo has `hacloud=1`.  However we know the HA gate is broken for different reasons, and anyway I am more inclined to trust your local testing. +1

**Pull request merged**
