### PR TITLE
crowbar-pacemaker: Code cleanups following post-merge review

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by aplanas** [comment]
The codeclimate complain makes somehow sense to me: use `%()` instead of `%''`. In either case: +1

**Comment by vuntz** [comment]
> The codeclimate complain makes somehow sense to me: use %() instead of %''.

I blame @aspiers ;-) Fixed.

**Comment by aspiers** [comment]
:-)  I agree with codeclimate too :-)

**Comment by aspiers** [comment]
+1

**Comment by aspiers** [comment]
Gate failed due to [c6: tempest.scenario.test_volume_boot_pattern.TestVolumeBootPatternV2.test_volume_boot_pattern Trello](https://trello.com/c/pXHuvAd3/112-c6-tempest-scenario-test-volume-boot-pattern-testvolumebootpatternv2-test-volume-boot-pattern); have forced a rebuild.

**Comment by aplanas** [comment]
Still +1

**Pull request merged**
