### PR TITLE
upgrade: fix pacemaker founder searchs

### PR DESCRIPTION
**Pull request by ilausuch**
When we introduced the new syncmarks for pacemaker
the founder was changed from a boolean indicating
that the node is a founder, to the fqdn of the founder

This results into #set_node_as_founder not working as expected
and unable to find the founder and change it to a new founder
properly

This patch refactors #set_node_as_founder to make sure we
set the new founder in the proper role for this cluster and
we set the drbd master (if exists) to the new_founder

(cherry picked from commit 7be1e3fc8ebaeca5c6ad1a5df4c1765801904c19)

Backport of https://github.com/crowbar/crowbar-ha/pull/291

### CODE REVIEW

**Comment by ilausuch** [comment]
[Port Itxaka's fixes for cluster founder to master](https://trello.com/c/lbXPqsNz/236-port-itxakas-fixes-for-cluster-founder-to-master)

**Comment by ilausuch** [comment]
[Port Itxaka's fixes for cluster founder to master](https://trello.com/c/lbXPqsNz/236-port-itxakas-fixes-for-cluster-founder-to-master)

**Comment by Itxaka** [comment]
Im...not sure of what I did

**Comment by Itxaka** [comment]
redid the PR on https://github.com/crowbar/crowbar-ha/pull/299, I still dont know what happened here, other than I broke it somehow.

**Pull request closed without merging**
