### PR TITLE
Drop support for hb_gui

### PR DESCRIPTION
**Pull request by vuntz**
This tool doesn't exist anymore on modern systems.

### CODE REVIEW

**Comment by vuntz** [comment]
Note that one setting in corosync.conf references it (use_mgmtd). Not sure if we should change it or not. @aspiers?

**Comment by aspiers** [comment]
Not sure.  BTW I'm deeply uncomfortable with the fact that [Travis has been broken on this repo for so many weeks](https://trello.com/c/bsOyEwZZ) :-(

**Comment by tboerger** [comment]
LGTM

**Comment by aspiers** [comment]
Actually this PR isn't covered by the Pacemaker cookbook test suite anyway.

> Note that one setting in corosync.conf references it (use_mgmtd). Not sure if we should change it or not. @aspiers?

I just asked on `#sleha`.  On SLE12 `corosync.conf(5)` doesn't mention the `service {}` section at all.

**Comment by vuntz** [comment]
@aspiers and I just read the code, and realized that the template I was talking about is SLE11 only anyway, so not relevant :-)

So this should be good.

**Comment by rsalevsky** [comment]
LGTM

**Pull request merged**
