### PR TITLE
Pacemaker cookbook

### LINKED ISSUE #16: Chef Pacemaker cookbook support for RHEL/CentOS and Chef 12
I have reworked the cookbooks to accomplish the following:

- Make them work with RHEL/CentOS versions 6.x
- Make them work with latest release of Chef 11 and 12
- Add test-kitchen tests to test a functioning two node cluster using Vagrant.
This is basically the second and last part of the earlier issue I had opened:
crowbar/barclamp-pacemaker#202

@aspiers suggested that I rebase my changes off crowbar-ha instead of barclamp-pacemaker.

### PR DESCRIPTION
**Pull request by ovaistariq**
Fixes #16

### CODE REVIEW

**Comment by ovaistariq** [comment]
@aspiers is there anything I can do here?

**Comment by ovaistariq** [comment]
@aspiers this looks like its still blocked for some reason. Anything you want me to do here?

**Comment by rsalevsky** [comment]
@ovaistariq As first step it would be create if you can fix all the hound style issues.

**Comment by aspiers** [comment]
@ovaistariq I'm so sorry for the delay - I keep meaning to look at this but I've been really struggling with workload so keep having to postpone.  @rsalevsky is right that it would be very helpful if you could fix the Hound CI style warnings; also I see that the branch now has conflicts so will need rebasing.

Also I have just submitted #30 which will help increase confidence that your changes won't introduce any regressions on our side.

**Comment by aspiers** [comment]
#30 has now been merged so please rebase this PR on top of that to ensure the test suite gets run by Travis.  Thanks again!

**Comment by rsalevsky** [comment]
If this should be still interesting please rebase and reopen.

**Pull request closed without merging**
