### PR TITLE
crowbar: Update for NodeObject.add_to_run_list changes

### PR DESCRIPTION
**Pull request by vuntz**
The states parameter is now useless, so drop it.

See crowbar/crowbar-core@84827646

Depends on https://github.com/crowbar/crowbar-core/pull/515

### CODE REVIEW

**Comment by toabctl** [comment]
beside the commit message, +1

**Comment by vuntz** [comment]
> @vuntz From the commit msg: The states parameter is now useless, so drop it.. Can you clarify what now means? mayb with a commit sha?

@toabctl I'm happy to do it, but a stupid question: do we have a standard way of referring to commits in other repos? Or should I just do "see sha in crowbar-core"?

**Comment by toabctl** [comment]
> @toabctl I'm happy to do it, but a stupid question: do we have a standard way of referring to commits in other repos? Or should I just do "see sha in crowbar-core"?

@vuntz Maybe ```see crowbar/crowbar-core@9f06b04``` which at least links in github and is imo human readable.

**Comment by vuntz** [comment]
Updated the commit message as suggested, no code change.

**Pull request merged**
