### PR TITLE
allow CIB objects with arbitrary unparsed definition strings (updated)

### PR DESCRIPTION
**Pull request by vuntz**
This is https://github.com/crowbar/crowbar-ha/pull/54 with some fixes.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
https://ci.suse.de/view/Cloud/view/Builds/job/openstack-mkcloud/14558/
test failed in nova boot with
```
Unable to establish connection to http://cluster-data.vc1.cloud.suse.de:8774/v2.1/
```
unrelated?

**Comment by vuntz** [comment]
Rebased (no code change).

**Comment by vuntz** [comment]
Last gating failure comes from this exception in glance:
```
2016-01-21 20:29:37.742 12802 INFO eventlet.wsgi.server [req-704ca80e-621d-49cf-a963-934e667dbd76 304fa8c6a4954d29af2f99357a5fb5a1 97f75ab531a449189e52e4f729edca4b - - -] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/eventlet/wsgi.py", line 483, in handle_one_response
    write(b''.join(towrite))
  File "/usr/lib/python2.7/site-packages/eventlet/wsgi.py", line 426, in write
    _writelines(towrite)
  File "/usr/lib64/python2.7/socket.py", line 334, in writelines
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/usr/lib/python2.7/site-packages/eventlet/greenio/base.py", line 376, in sendall
    tail = self.send(data, flags)
  File "/usr/lib/python2.7/site-packages/eventlet/greenio/base.py", line 359, in send
    total_sent += fd.send(data[total_sent:], flags)
error: [Errno 9] Bad file descriptor
```

**Comment by bmwiedemann** [comment]
last test https://ci.suse.de/view/Cloud/view/Worker/job/openstack-mkcloud/15219/ said
```
Multi DNS server test failed
```

**Comment by aspiers** [comment]
I'm not sure but I think @vuntz was referring to the previous build [openstack-mkcloud#15170: develcloud6 (4/openvswitch/-t -s/all_noreboot/crowbar/crowbar-ha:56:46c203aed553b3619734a30f5c0cfe47d13723b3:master 1)](https://ci.suse.de/job/openstack-mkcloud/15170/console)

Please can we get in the habit of filing cards in the Jenkins green board for new failures?  It makes it much easier to keep track of where we are with all these.

**Comment by aspiers** [comment]
Filed [c6-ha: glance image list/delete fail in cct Trello](https://trello.com/c/LMNNosU6/124-c6-ha-glance-image-list-delete-fail-in-cct)

**Comment by aspiers** [comment]
Filed [c6-ha: Multi DNS server test failed](https://trello.com/c/QLwOdH1r/125-c6-ha-multi-dns-server-test-failed)

**Comment by aspiers** [comment]
This PR moves a whole load of duplicated code out from `maybe_modify_resource` in each LWRP, into a shared `standard_maybe_modify_resource`, which is good, but it conflicts with #3 which wants to insert more code into each `maybe_modify_resource`.  @vuntz I have resolved this conflict manually but I'm not sure how to deal with the PRs.

**Comment by aspiers** [comment]
Gate failed again, now due to [c6-ha: Waiting for 'testvm booted and ping returned' timed out in testsetup step (Trello)](https://trello.com/c/30w2SCA0/128-c6-ha-waiting-for-testvm-booted-and-ping-returned-timed-out-in-testsetup-step)

**Comment by aspiers** [comment]
@vuntz Needs rebasing :-(

**Comment by vuntz** [comment]
Rebased

**Comment by nkrinner** [comment]
Gating failed, I think recently merged https://github.com/crowbar/crowbar-ha/pull/51 was not present in the build environment.

**Comment by aspiers** [comment]
I'm +1 on this now.  Have forced a rebuild in case it tells us anything useful.

**Comment by nkrinner** [comment]
Gating fails again, well-known bug is already tracked here: https://trello.com/c/30w2SCA0 : "c6-ha: Waiting for 'testvm booted and ping returned' timed out in testsetup step"

As this is unrelated to the code change, I am +1 on the pull request.

**Pull request merged**
